### ISSUE TITLE
BUG - Purchases for Train Employees / Hire Employees can be bought when the user can't afford them

### ISSUE THREAD

**Issue by 3eak** [3eak/paper-clicker#21]
Solution - 

Find the divs for the Hire Employees and Train Employees buttons and add additional conditions for the rendering of them and what happens when you click them. See `renderChopWoodButton()` for an example of how to do this - effectively the solution will be a replica of that but with changed numbers to reflect the prices of Training/Hiring.

**Comment by ReeceKay** [comment]
All done
