### ISSUE TITLE
Possible to 'Hire Employees' and 'Train Employees' even if you don't have the required resources

### ISSUE THREAD

**Issue by BenParsley** [3eak/paper-clicker#26]
The player shouldn't have the ability to hire employees if don't have £500 in their account, this also occurs when the user wants to 'Train employees', they can do so without having £1000

-simply check if the user has the correct amount of money if they click the button-

**Comment by 3eak** [comment]
Is this a duplicate of issue #21 ?

**Comment by BenParsley** [comment]
oh no
